config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'users#home'
  resources :users do
  end
  get 'home', to: 'users#home', as: 'home'
  get 'money_transfers', to: 'wallets#money_transfers', as: 'money_transfers'
  post 'confirm_transaction/:id', to: 'wallet_transactions#confirm_transaction', as: 'confirm_transaction'
  resources :wallets
  resources :invites
  resources :wallet_transactions

  get :documentation, to: 'users#documentation', as: 'documentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  belongs_to :wallet
  belongs_to :user

  def proces(params, user)
    Invite.transaction do
      update(params)
      wallet.users << user if params[:is_confirmed] == 'true'
    end
  end
end

app/controllers/invites_controller.rb
# frozen_string_literal: true

class InvitesController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :set_invite, only: %i[show edit update destroy]
  before_action :set_wallet_for_invite, only: %i[new create]

  # GET /invites
  # GET /invites.json
  def index
    @invites = current_user.invites.where(is_declined: nil).all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show; end

  # GET /invites/new
  def new
    @invite = NewInvite.new
  end

  # GET /invites/1/edit
  def edit
    @from_user = User.find(@invite.from_id)
    @wallet_from = @invite.wallet
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = NewInvite.new(invite_params, current_user)
    @invite.call
    respond_with @invite, location: wallet_path(id: invite_params[:wallet_id])
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.proces(confirmed_params, current_user)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  # def destroy
  #   @invite.destroy
  #   respond_to do |format|
  #     format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invite
    @invite = Invite.find(params[:id])
  end

  def set_wallet_for_invite
    table = Wallet.table_name
    privacy_query = "(#{table}.is_private is true AND " \
                    " #{table}.admin_id = #{current_user.id}) " \
                    " OR #{table}.is_private is false"
    @wallet = current_user.wallets.where(privacy_query)
                          .where.not(type: 'Personal')
                          .find(params[:wallet_id] || params['new_invite'][:wallet_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invite_params
    params.require(:new_invite).permit(:wallet_id, :user_email, :message, :daily_limit)
  end

  def confirmed_params
    params.permit(:is_confirmed, :is_declined)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_with(model: invite, local: true) do |form| %>
  <% if invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing Invite</h1>

<b>Invite from:</b> <%= link_to @from_user.name, @from_user %><br><br>
<b>Invite to <%= @wallet_from.type.downcase %> wallet:</b> <%= @wallet_from.identity %><br><br>

<td><%= link_to 'Confirm', invite_path(@invite.id, is_confirmed: true, is_declined: false, wallet_id: @invite.wallet_id), method: :patch, data: { confirm: 'Are you sure?' } %></td>
 | <td><%= link_to 'Decline', invite_path(@invite.id, is_confirmed: false, is_declined: true, wallet_id: @invite.wallet_id), method: :patch, data: { confirm: 'Are you sure?' } %></td>


 | <%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invites</h1>

<table>

    <% @invites.each do |invite| %>

    <tr>
      <td><%= invite.message %> - 
        <%= link_to 'Show invite', edit_invite_path(invite) %></td>
      </tr>
    <% end %>
</table>

app/views/invites/new.html.erb
<h1>New Invite</h1>

<div class="depot_form">
	<% if flash[:alert] %>
		<p id="notice"><%= flash[:alert] %></p>
<% end %>

<%= form_for(@invite, url: invites_path) do |f| %>
 <%= f.hidden_field :wallet_id, value: params[:wallet_id] %>

<table>

    <tr>
        <td>
            <%= f.label :user_email %><br>
            <%= f.email_field :user_email %>
        </td>
    </tr>
    <tr>
        <td>
            <%= f.label :message, 'Write message here' %>:<br>
            <%= f.text_field :message %>
        </td>
    </tr>
    <% if @wallet.is_a?(Family) %>
        <tr>
            <td>
                <%= f.label :daily_limit, 'User daily limit' %>:<br>
                <%= f.text_field :daily_limit %>
            </td>
        </tr>
    <% end %>

</table>
  <%= f.submit %>
<% end %><br><br>
	

<%= link_to 'Back to wallet', wallet_path(id: params[:wallet_id]) %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'To invites', invites_path %>