config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'users#home'
  resources :users do
  end
  get 'home', to: 'users#home', as: 'home'
  get 'money_transfers', to: 'wallets#money_transfers', as: 'money_transfers'
  post 'confirm_transaction/:id', to: 'wallet_transactions#confirm_transaction', as: 'confirm_transaction'
  resources :wallets
  resources :invites
  resources :wallet_transactions

  get :documentation, to: 'users#documentation', as: 'documentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :wallets
  has_and_belongs_to_many :wallet_transactions
  has_many :invites
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    session[:email] = params[:email]
  end

  # POST /resource
  def create
    super
    session[:email] = params['user']['email']
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
    session[:email] = params['user']['email']
  end

  # DELETE /resource/sign_out
  def destroy
    super
    session[:email] = nil
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: :home
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /home
  def home
    @user = current_user
  end

  # GET /documentation
  def documentation; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/documentation.html.erb
<p>Registered users can create three types of wallets.</p>

<p><b>Personal wallet.</b> The user can replenish the wallet and transfer money from it to any other.</p>

<p><b>Team wallet </b>(for example, a company wallet, or a general collection for certain purposes). It can be private and public. If the wallet is private, only its creator can invite users. Otherwise, all its members can invite other users. Only the creator can to transfer money from this wallet. All users can replenish it.</p>

<p><b>Family wallet. </b>Only the creator can invite other users. The creator of the wallet has an unlimited limit to receive the available money from wallet. Invited members have a daily limit set by the wallet's creator. However, if the user (not the creator) has a positive balance in this wallet, which is above the limit, he can use it. All users can replenish it.</p>

<p>A money tranfer between is possible <b>only between wallets with the same currency</b>.</p>

<p>For each operation is charged a tax, which depends on the size of the transferred money. When transferring to someone else’s wallet, the user can choose who will pay the tax. </p>

<p><i>But!
(There will be a tax for replenishing personal wallet from outside the system, but it does not affect the final amount. Because, for example, each new user has an unlimited budget outside the system from which personal purses are allegedly replenished and a tax is paid)</i></p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "My Invites (#{@user.invites.where(is_declined: nil).count})", invites_path %> <hr>

<table align='center'>

    <tr>
        <td align='center'>
            <%= link_to wallets_path do %>
                <%= image_tag "all.png", class: "wallet_logo" %>
            <% end %>
        </td>
    </tr>
    <tr>
    <td align='center'> My wallets </td>
</tr>
</table>

<hr>

<h1 align='center'> Create new wallet: </h1><br><br>

<table align='center'>

<tr>
    <td align='center'>
        <%= link_to new_wallet_path(type: 'Personal') do %>
            <%= image_tag "Personal.png", class: "wallet_logo" %>
        <% end %>
    </td>

    <td align='center'>
        <%= link_to new_wallet_path(type: 'Team') do %>
            <%= image_tag "Team.png", class: "wallet_logo" %>
        <% end %>
    </td>

    <td align='center'>
        <%= link_to new_wallet_path(type: 'Family') do %>
            <%= image_tag "Family.png", class: "wallet_logo" %>
        <% end %>
    </td>
</tr>
<tr>
    <td align='center'> New Personal Wallet </td>
    <td align='center'> New Team Wallet </td>
    <td align='center'> New Family Wallet </td>
</tr>

</table>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>

      </tr>
      
    <% end %>
    
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', users_path %>