config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'users#home'
  resources :users do
  end
  get 'home', to: 'users#home', as: 'home'
  get 'money_transfers', to: 'wallets#money_transfers', as: 'money_transfers'
  post 'confirm_transaction/:id', to: 'wallet_transactions#confirm_transaction', as: 'confirm_transaction'
  resources :wallets
  resources :invites
  resources :wallet_transactions

  get :documentation, to: 'users#documentation', as: 'documentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/wallet_transactions_controller.rb
# frozen_string_literal: true

class WalletTransactionsController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :set_wallet_transaction, only: %i[show edit update destroy]

  # GET /wallet_transactions
  # GET /wallet_transactions.json
  # def index
  #   @wallet_transactions = WalletTransaction.all
  # end

  # GET /wallet_transactions/1
  # GET /wallet_transactions/1.json
  def show
    @user = current_user
    @initiator = User.find(@wallet_transaction.initiator_id)
    if @wallet_transaction.wallet_from_id.present?
      @wallet_from = Wallet.find(@wallet_transaction.wallet_from_id).identity
    end
    @wallet_to = Wallet.find(@wallet_transaction.wallet_to_id).identity
  end

  # GET /wallet_transactions/new
  def new
    @user = current_user
    t = Wallet.table_name
    query = "#{t}.admin_id = #{current_user.id} or #{t}.type = 'Family'"
    @wallets_from = current_user.wallets.where(query)
  end

  # POST /confirm_transaction/:id
  def confirm_transaction
    @transaction = WalletTransaction.new_transaction.find_by(initiator_id: current_user.id)
    raise StandardError, 'transaction not found' if @transaction.blank?
    
    @transaction.update(status: :in_progress)

    ProcessTransactionWorker.perform_async(@transaction.id)
    respond_with @transaction, location: @transaction
  end

  # GET /wallet_transactions/1/edit
  def edit; end

  # POST /wallet_transactions
  # POST /wallet_transactions.json
  def create
    @wallet_transaction = TransactionCreate.perform(wallet_transaction_params,
                                                     current_user)
    respond_to do |format|
      if @wallet_transaction.save
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully created.' }
        format.json { render :show, status: :created, location: @wallet_transaction }
      else
        format.html { render :new }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallet_transactions/1
  # PATCH/PUT /wallet_transactions/1.json
  def update
    respond_to do |format|
      if @wallet_transaction.update(wallet_transaction_params)
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet_transaction }
      else
        format.html { render :edit }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_transactions/1
  # DELETE /wallet_transactions/1.json
  def destroy
    @wallet_transaction.destroy
    respond_to do |format|
      format.html { redirect_to wallet_transactions_url, notice: 'Wallet transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wallet_transaction
    @wallet_transaction = current_user.wallet_transactions.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wallet_transaction_params
    params.require(:wallet_transaction).permit(:type, :wallet_to_id,
                                               :wallet_from_id, :wallet_to,
                                               :tax_paid_by_the_recipient,
                                               :transfered_money)
  end
end

app/helpers/wallet_transactions_helper.rb
module WalletTransactionsHelper
end

app/views/wallet_transactions/_form.html.erb
<%= form_with(model: wallet_transaction, local: true) do |form| %>
  <% if wallet_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet_transaction.errors.count, "error") %> prohibited this wallet_transaction from being saved:</h2>

      <ul>
      <% wallet_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallet_transactions/edit.html.erb
<h1>Editing Wallet Transaction</h1>

<%= render 'form', wallet_transaction: @wallet_transaction %>

<%= link_to 'Show', @wallet_transaction %> |
<%= link_to 'Back', wallet_transactions_path %>

app/views/wallet_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallet Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallet_transactions.each do |wallet_transaction| %>
      <tr>
        <td><%= link_to 'Show', wallet_transaction %></td>
        <td><%= link_to 'Edit', edit_wallet_transaction_path(wallet_transaction) %></td>
        <td><%= link_to 'Destroy', wallet_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet Transaction', new_wallet_transaction_path %>

app/views/wallet_transactions/new.html.erb
<h1><%= params[:type].humanize  %></h1>

<div class="depot_form">
	<% if flash[:alert] %>
		<p id="notice"><%= flash[:alert] %></p>
<% end %>

<%= form_for('wallet_transaction', url: wallet_transactions_path) do |f| %>
 <%= f.hidden_field :type, value: params[:type] %>

<table>

    <% if params[:type] == 'replenish_your_wallet' %>
        <% if @user.wallets.present? %>
            <tr>
                <td>
                    <%= f.label :wallet_to_id, 'Select your wallet' %>:
                    <%= f.select(:wallet_to_id, @user.wallets.collect { |w| ["#{w.identity} (#{w.capital})", w.id] }) %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :transfered_money, 'Transfered money' %>:
                    <%= f.number_field :transfered_money %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.submit %>
                </td>
            </tr>
              
        <% else %>
            You have not any wallet!
            <%= link_to 'Create Your Personal Wallet', new_wallet_path(type: 'Personal') %>
        <% end %>
    <% end %>

    <% if params[:type] == 'between_your_wallets' %>
        <% if @wallets_from.present? %>
            <tr>
                <td>
                    <%= f.label :wallet_from_id, 'Select wallet from' %>:
                    <%= f.select(:wallet_from_id, @wallets_from.collect { |w| ["#{w.identity} (#{w.capital})", w.id] }) %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :wallet_to_id, 'Select wallet to' %>:
                    <%= f.select(:wallet_to_id, @user.wallets.collect { |w| ["#{w.identity} (#{w.capital})", w.id] }) %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :transfered_money, 'Transfered money' %>:
                    <%= f.number_field :transfered_money %>
                </td>
            </tr>
              <tr>
                <td>
                    <%= f.submit %>
                </td>
            </tr>
        <% else %>
            You have not any wallet!
            <%= link_to 'Create Your Personal Wallet', new_wallet_path(type: 'Personal') %>
        <% end %>
    <% end %>

    <% if params[:type] == 'to_another_wallet' %>
        <% if @wallets_from.present? %>
            <tr>
                <td>
                    <%= f.label :wallet_from_id, 'Select wallet from' %>:
                    <%= f.select(:wallet_from_id, @wallets_from.collect { |w| ["#{w.identity} (#{w.capital})", w.id] }) %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :wallet_to, 'Paste wallet to' %>:
                    <%= f.text_field :wallet_to, placeholder: 'USD-****************' %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :tax_paid_by_the_recipient, 'tax paid by the recipient' %>:
                    <%= f.check_box :tax_paid_by_the_recipient, {}, true, false %>
                </td>
            </tr>
            <tr>
                <td>
                    <%= f.label :transfered_money, 'Transfered money' %>:
                    <%= f.number_field :transfered_money %>
                </td>
            </tr>
               <tr>
                <td>
                    <%= f.submit %>
                </td>
            </tr>
        <% else %>
            You have not any wallet!
            <%= link_to 'Create Your Personal Wallet', new_wallet_path(type: 'Personal') %>
        <% end %>      
    <% end %>


</table>

<% end %>
	

<%= link_to 'Back', wallets_path %>

<hr>

<font size='1' color='red'><b>Transaction plans:</b><br></font>

<% TransactionPlan.all.each do |plan| %>
<font size='1' color='grey'><%= "from #{plan.from}  to #{plan.to || 'and more' } tax is: #{plan.price} " %></font><br>

<% end %>

app/views/wallet_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<b>Type: </b><%= @wallet_transaction.transaction_type.humanize %><br><br>
<b>Initiator: </b><%= link_to @initiator.name, @initiator %><br><br>

<b>Status: </b><%= @wallet_transaction.status.humanize %> 
<% if @wallet_transaction.in_progress? %>

    - <%= link_to 'refresh', @wallet_transaction %> 
<% end %>

<% if @wallet_transaction.failed? %> 

    <i>(<%= @wallet_transaction.error_message %>)</i>
<% end %><br><br>   

<b>Sum of transfer: </b><%= "#{@wallet_transaction.transfered_money} #{@wallet_transaction.currency_id}"  %><br>
<b>Transaction tax: </b><%= "#{@wallet_transaction.tax}  #{@wallet_transaction.currency_id}" %><br><br><br>

<% if @wallet_transaction.replenish_your_wallet? %>
    <b>To your wallet:</b>  <%= @wallet_to %>
<% end %>

<% if @wallet_transaction.between_your_wallets? %>
    <b>From your wallet:</b>  <%= @wallet_from %> => 
    <b>To your wallet:</b>  <%= @wallet_to %><br>
<% end %>

<% if @wallet_transaction.to_another_wallet? %>
    <b>From your wallet:</b>  <%= @wallet_from %> => 
    <b>To wallet:</b>  <%= @wallet_to %><br>
    <% if @wallet_transaction.tax_paid_by_the_recipient %>
        <i>Tax paid by the recipient</i>
    <% end %>

<% end %>
<br><br><br>

<% if @wallet_transaction.new_transaction? %>

    <%= link_to 'Confirm', confirm_transaction_path(@wallet_transaction), method: :post, data: 'are you sure?' %> 
<% end %>