config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'users#home'
  resources :users do
  end
  get 'home', to: 'users#home', as: 'home'
  get 'money_transfers', to: 'wallets#money_transfers', as: 'money_transfers'
  post 'confirm_transaction/:id', to: 'wallet_transactions#confirm_transaction', as: 'confirm_transaction'
  resources :wallets
  resources :invites
  resources :wallet_transactions

  get :documentation, to: 'users#documentation', as: 'documentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  TransferResult = Struct.new(:status, :error_message)

  has_and_belongs_to_many :users
  has_and_belongs_to_many :wallet_transactions
  belongs_to :currency
  has_many :invites

  scope :public_wallets, -> { where(is_private: false) }
  scope :no_pesonal, -> { where.not(type: 'Personal') }

  def created(params, owner)
    params[:wallet_identity] = wallet_identity(params)
    Wallet.transaction do
      Factory.new.call(params, owner)
    end
  end

  def withdraw_money(transfer, sum_for_transfer)
    withdraw_error = validate_error(transfer, sum_for_transfer)
    return withdraw_error if withdraw_error.present?

    self.capital -= sum_for_transfer
    save!
    TransferResult.new(:done, nil)
  end

  def receiving_money(_transfer, sum_for_transfer)
    self.capital += sum_for_transfer
    save!
    TransferResult.new(:done, nil)
  end

  def encrypte_pin(pin)
    crypt.encrypt_and_sign(pin)
  end

  def decrypt_pin
    crypt.decrypt_and_verify(encrypted_pin)
  end

  def crypt
    key = Rails.application.config.secret_key
    ActiveSupport::MessageEncryptor.new(key)
  end

  def wallet_identity(params)
    "#{params[:currency_id]}-#{SecureRandom.hex(8)}"
  end

  def validate_error(transfer, sum_for_transfer)
    if self.capital <= sum_for_transfer
      TransferResult.new(:failed, 'not enough money')
    elsif admin_id != transfer.initiator_id
      TransferResult.new(:failed,
                         'Only admin can withdraw money from this wallet')
    end
  end
end

class Factory
  def call(params, owner)
    params[:type].constantize.new.new_wallet(params, owner)
  end
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wallet, only: %i[show edit update destroy]

  # GET /wallets
  # GET /wallets.json
  def index
    if params[:user_id].blank?
      @wallets = current_user.wallets
    else
      user = User.find(params[:user_id])
      @wallets = user.wallets.public_wallets
    end
  end

  # GET /wallets/1
  # GET /wallets/1.json
  def show
    @user = current_user
  end

  # GET /money_transfers
  def money_transfers; end

  # GET /wallets/new
  def new
    @wallet = current_user.wallets.new
  end

  # GET /wallets/1/edit
  def edit; end

  # POST /wallets
  # POST /wallets.json
  def create
    @wallet = Wallet.new

    respond_to do |format|
      if @wallet.created(wallet_params, current_user)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully created.' }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1
  # PATCH/PUT /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.json
  # def destroy
  #   @wallet.destroy
  #   respond_to do |format|
  #     format.html { redirect_to wallets_url, notice: 'Wallet was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wallet
    if params[:user_id].blank?
      @wallet = current_user.wallets.find(params[:id])
    else
      user = User.find(params[:user_id])
      @wallet = user.wallets.public_wallets.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wallet_params
    params.require(:wallet).permit(:description, :type, :currency_id, :is_private)
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_with(model: wallet, local: true) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<%= link_to 'Operations with wallets', money_transfers_path %>
<hr>

<p id="notice"><%= notice %></p>

<h1>Wallets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallets.each do |wallet| %>
      <tr>
        <td> <%= image_tag "#{wallet.type}.png", class: "wallet_icon" %> </td>
        <td>

          <b><%= wallet.type %> (<%= wallet.capital %> <%= wallet.currency_id %>)</b> - 
          <%= wallet.identity %> - <%= wallet.description %> - 
          <%= link_to 'Show', wallet_path(id: wallet.id) %> <br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wallets/money_transfers.html.erb
<%= link_to 'My wallets', wallets_path %>
<hr>

<h1 align='center'> Operations with your wallets: </h1><br><br>

<table align='center'>

<tr>
    <td align='center'>
        <%= link_to new_wallet_transaction_path(type: :replenish_your_wallet) do %>
            <%= image_tag "me.png", class: "wallet_logo" %>
        <% end %>
    </td>

    <td align='center'>
        <%= link_to new_wallet_transaction_path(type: :between_your_wallets) do %>
            <%= image_tag "between.png", class: "wallet_logo" %>
        <% end %>
    </td>

    <td align='center'>
        <%= link_to new_wallet_transaction_path(type: :to_another_wallet) do %>
            <%= image_tag "another.png", class: "wallet_logo" %>
        <% end %>
    </td>
</tr>
<tr>
    <td align='center'> Replenish your wallet</td>
    <td align='center'> Between your wallets</td>
    <td align='center'> To another wallet </td>
</tr>

</table>

app/views/wallets/new.html.erb
<div class="depot_form">
	<% if flash[:alert] %>
		<p id="notice"><%= flash[:alert] %></p>
<% end %>

<%= form_for(@wallet, url: wallets_path) do |f| %>
 <%= f.hidden_field :type, value: params[:type] %>

<table>
    <tr>
        <td>
            <%= f.label :description, 'Add description' %>:
            <%= f.text_field :description %>
        </td>
    </tr>
    <tr>
            <%= f.label :currency, 'Select currency' %>:
            <%= f.select(:currency_id, Currency.all.collect { |c| [c.id, c.id] }) %>
        </td>
    </tr>


    <% if params[:type] == 'Team' %>
        <tr>
                <%= f.label :is_private, 'Select privacy' %>:
                <%= f.select(:is_private, [['private', true], ['public', false]]) %>
            </td>
        </tr>
    <% end %>




</table>
  <%= f.submit %>
<% end %>
	

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<%= link_to 'Back', wallets_path %> <hr>

<b><%= image_tag "#{@wallet.type}.png", class: "wallet_icon" %>
 (<%= @wallet.capital %> <%= @wallet.currency_id %>)</b> - <%= @wallet.identity %> - <%= @wallet.description %> <br><br>
<% if @wallet.type != 'Personal' %>
    <% if @wallet.type == 'Family' %> 
    <b> Your daily limit: </b> <%= @wallet.user_limit(@user.id) || 'with no restrictions'  %> <br><br>
    <b> Your budget: </b> <%= @wallet.user_budget(@user.id)  %> <br><br>

       <b> Your family: </b>
    <% else %>
       <b> Your team:</b>
    <% end %><br>
    <% @wallet.users.each do |user| %>
        - <%= link_to user.name, user %> - <%= user.email %> <br>
    <% end %><br> <br>
    <% if (@wallet.admin_id == @user.id && @wallet.is_private) || !@wallet.is_private %>
        <%= link_to 'Invite user to this wallet', new_invite_path(wallet_id: @wallet.id) %><br><br>
    <% end %>

    <b>Not confirmed invites: </b><br>
    <% @wallet.invites.where(is_confirmed: false).each do |invite| %>
        - <%= link_to invite.user.name, invite.user %> - <%= invite.created_at %> <br>
    <% end %><br> <br>
<% end %>
<hr>

<b> Transactions: </b><br> <br>
<table>
    <tr>
        <% @wallet.wallet_transactions.each do |t| %>

            <td><% if t.wallet_to_id != @wallet.id  %> 
                <font color="red"><b><=====</b></font>
            <% else %>
                <font color="green"><b>=====></b></font> 
            <% end %></td>
            <td>
            <% if t.wallet_from_id.present? %> 
            - from: <b><%= Wallet.find(t.wallet_from_id).identity %></b>
            <% end %> 
            
            - <%= t.transaction_type.humanize %> 
            - <b><%= "#{t.transfered_money} #{t.currency_id}" %> </b>
            - <%= t.status.humanize %>

            <%= link_to 'more details', t %>

            <br> <br>
            </td>
    </tr>
    <% end %>

</table>